Lab.API/Lab.API.Route/Models/ErrorViewModel.cs
namespace Lab.API.Route.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Lab.API/Lab.API.Route/Models/Product.cs
namespace Lab.API.Route.Models
{
    public class Product
    {
        public int Id { get; set; }

        public string? Name { get; set; }


    }
}

Lab.API/Lab.API.Route/Areas/TestAll/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace Lab.API.Route.Areas.TestAll.Controllers
{
    [Area("TestAll")]
    public class HomeController : Controller
    {
       
        public IActionResult Index()
        {
            return View();
        }
    }
}

Lab.API/Lab.API.Route/Controllers/HomeController.cs
using Lab.API.Route.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Docs.Samples;
using System.Diagnostics;

namespace Lab.API.Route.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        public IActionResult Sourse()
        {
            
            var url = Url.Action("Destination");
            return ControllerContext.MyDisplayRouteInfo(" ", $"url={url}");

        }

        // Home / Destination
        public IActionResult Destination()
        {
            return ControllerContext.MyDisplayRouteInfo();
        }

        // Home/UrlGet
        public IActionResult UrlGet()
        {
            var url = Url.Action("Buy", "Product", new { id = 17, color = "red" });
            return Content(url);
        }


        // Rest API 屬性路由 , HomeController 會比對跟慣例路由相近的
        [Route("")]
        [Route("Home")]
        [Route("Home/Index")]
        [Route("Home/Index/{id?}")]
        public IActionResult Index2(int? id)
        {
            return ControllerContext.MyDisplayRouteInfo(id);
        }

        [Route("Home/About")]
        [Route("Home/About/{id?}")]
        public IActionResult About(int? id)
        {
            return ControllerContext.MyDisplayRouteInfo(id);
        }

        // 像 page 這種是系統保留關鍵字,用在路由會讓系統衝突
        [Route("/articles/{page}")]
        public IActionResult ListArticles(int page)
        {
            return ControllerContext.MyDisplayRouteInfo(page);
        }


        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Lab.API/Lab.API.Route/Controllers/Product33Controller.cs
using Lab.API.Route.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Docs.Samples;

namespace Lab.API.Route.Controllers
{
    public class Product33Controller : Controller
    {
            // 這樣寫都會符合預設路由 {controller=Home}/{action=Index}/{id?} 
            public IActionResult Edit(int id)
            { 
               return ControllerContext.MyDisplayRouteInfo(id);

            }
            // Edit(int id) 負責顯示表單 , Edit(int id, Product product) 負責處理
            [HttpPost]
            public IActionResult Edit(int id, Product product)
            {
                return ControllerContext.MyDisplayRouteInfo(id, product.Name);
          
        }


        [HttpGet("/products3")]
        public IActionResult ListProducts()
        {
            return ControllerContext.MyDisplayRouteInfo();
        }

        [HttpPost("/products3")]
        public IActionResult CreateProduct(Product myProduct)
        {
            return ControllerContext.MyDisplayRouteInfo(myProduct.Name);
        }


        [HttpPost]
        [ValidateAntiForgeryToken] // 驗證
        public IActionResult EditProduct(int id, Product product)
        {
            if (ModelState.IsValid)
            {  
                // 用 ViewData 傳更新成功的訊息 
                ViewData["Message"] = $"Successful edit of customer {id}";
                // RedirectToAction就是傳統跳轉 View 的方法
                return RedirectToAction("Index");
            }
            return View(product);
        }

    }
}

Lab.API/Lab.API.Route/Controllers/TestController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Docs.Samples;

namespace Lab.API.Route.Controllers
{
    [Route("Store")]
    [Route("[controller]")]
    [ApiController]
    public class TestController : Controller
    {

        // 同時符合 Test/Buy , Store/Buy , Test/Checkout , Store/Checkout
        [HttpPost("Buy")]
        [HttpPost("Checkout")]  
        public IActionResult Buy()
        {
            return ControllerContext.MyDisplayRouteInfo();
        }

        [HttpGet("{id}")]   // GET /api/Test/xyz
        public IActionResult GetProduct(string id)
        {
            return ControllerContext.MyDisplayRouteInfo(id);
        }

        // 路由可以限制變數的型態
        [HttpGet("int/{id:int}")] // GET /api/Test/int/3
        public IActionResult GetIntProduct(int id)
        {
            return ControllerContext.MyDisplayRouteInfo(id);
        }

        // 這裡路由沒限制,但是參數型態是 int 
        // 這樣當今天丟其他型態的參數就會報錯誤 所以在路由限制我覺得比較方便

        [HttpGet("int2/{id}")]  // GET / api / Test / int2 / abc
        public IActionResult GetInt2Product(int id)
        {
            return ControllerContext.MyDisplayRouteInfo(id);
        }
    }
}

Lab.API/Lab.API.Route/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Lab.API/Lab.API.Route/Views/Product33/Edit.cshtml
<p>Hello</p>

Lab.API/Lab.API.Route/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Lab.API.Route</title>
    <script type="importmap"></script>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Lab.API.Route.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Lab.API.Route</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Product33" asp-action="Edit">Product33</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="TestAll" asp-controller="Home" asp-action="Index">TestAll</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2026 - Lab.API.Route - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>